targets:
  $default:
    builders:
      libc_bindings_generator|libc_platform_binding_gen:
        generate_for:
          - lib/src/bindings/libc_arm.dart
          - lib/src/bindings/libc_arm64.dart
          - lib/src/bindings/libc_i386.dart
          - lib/src/bindings/libc_amd64.dart
        options:
          distro: sid
          windowsLlvmPath: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\Llvm\\x64\\"
          sevenZipCommand: "C:\\Program Files\\7-Zip\\7z.exe"
          ffigen-options:
            headers:
              entry-points:
                - 'errno.h'
                - 'fcntl.h'
                - 'unistd.h'
                - 'termios.h'
                - 'sys/ioctl.h'
                - 'sys/types.h'
                - 'sys/stat.h'
                - 'sys/epoll.h'
                - 'linux/gpio.h'
            functions:
              include:
                - ioctl
                - epoll_create
                - epoll_create1
                - epoll_ctl
                - epoll_wait
                - __errno_location
                - open
                - close
                - read
              rename:
                '__errno_location': 'errno_location'
              symbol-address:
                include:
                  - epoll_ctl
                  - epoll_wait
                  - __errno_location
                  - read
              leaf:
                include:
                  - '.*'
            structs:
              include:
                - epoll_event
                - gpiochip_info
                - gpio_v2_line_values
                - gpio_v2_line_attribute
                - gpio_v2_line_config_attribute
                - gpio_v2_line_config
                - gpio_v2_line_request
                - gpio_v2_line_info
                - gpio_v2_line_info_changes
                - gpio_v2_line_event
                - gpioline_info
                - gpioline_info_changed
                - gpiohandle_request
                - gpiohandle_config
                - gpiohandle_data
                - gpioevent_request
                - gpioevent_data
            unions:
              include:
                - epoll_data
            enums:
              include:
                - 'EPOLL_EVENTS'
            unnamed-enums: 
              include:
                - 'EPOLL.*'
                - 'O_.*'
                - 'GPIO.*'
            globals:
              exclude:
                - '.*'
            macros:
              include:
                - 'EPOLL_.*'
                - 'O_.*'
                - 'GPIO.*'