targets:
  $default:
    builders:
      libc_bindings_generator|libc_platform_binding_gen:
        generate_for:
          - lib/src/bindings/libc_arm.dart
          - lib/src/bindings/libc_arm64.dart
          - lib/src/bindings/libc_i386.dart
          - lib/src/bindings/libc_amd64.dart
        options:
          distro: sid
          windowsLlvmPath: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\Llvm\\x64\\"
          sevenZipCommand: "C:\\Program Files\\7-Zip\\7z.exe"