name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.4
  libc_bindings_generator:
    path: ../
  pedantic: ^1.10.0
  test: ^1.16.0
