name: flutter_gpiod_example
description: Demonstrates how to use the flutter_gpiod plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0
  flutter_gpiod:
    path: ../
