name: linux_spidev
description: Dart package for accessing SPI on Linux using the spidev interface.
version: 0.1.0
author: Hannes Winkler
homepage: https://ardera.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.12.2
  libc_bindings_generator:
    path: ../libc_bindings_generator

dependencies:
  ffi: ^1.0.0
  meta: ^1.1.8
  tuple: ^2.0.0
  path: ^1.7.0