name: _ardera_common_libc_bindings
description: |
  Some common libc bindings. (ioctl, gpio, stuff like that)

version: 0.2.0
repository: https://github.com/ardera/flutter_packages/

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.20.1
  ffigen: ^7.2.10

dependencies:
  build_runner: ^2.1.7
  ffi: ^2.0.1
  meta: ^1.7.0
  tuple: ^2.0.1
