builders:
  libc_platform_binding_gen:
    import: "package:libc_bindings_generator/builder.dart"
    builder_factories: ["libcPlatformBackendBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source
    auto_apply: none
    defaults:
      options:
        distro: sid