name: linux_serial
description: Dart package for accessing serial on Linux.
version: 0.0.1
homepage: https://ardera.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.12.2
  libc_bindings_generator:
    path: ../libc_bindings_generator

dependencies:
  ffi: ^1.0.0
  meta: ^1.3.0
  tuple: ^2.0.0
  path: ^1.8.0
  async: ^2.5.0
  computer: ^2.0.0
  synchronized: ^3.0.0