name: libc_bindings
description: Dart bindings for common libc library functions.
version: 0.0.1
homepage: https://ardera.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  pedantic: ^1.10.0

dev_dependencies:
  build_runner: ^1.12.2
  test: ^1.16.0
  libc_bindings_generator:
    path: ../libc_bindings_generator
