name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: panda

    steps:
      - uses: actions/checkout@v2

      - name: Setup flutter SDK
        uses: subosito/flutter-action@v2.3.0
             
      - name: Setup melos
        run: dart pub global activate melos
      
      - name: flutter precache
        run: flutter precache

      - name: melos bootstrap
        run: dart pub global run melos bootstrap
        
      - name: flutter format
        run: dart pub global run melos exec flutter format --output=none --set-exit-if-changed .
        
      - name: flutter analyze
        run: dart pub global run melos exec flutter analyze --fatal-infos
        
      - name: melos test
        run: dart pub global run melos test
        
      - name: run flutter_gpiod_test_app on ODROID C4
        working-directory: packages/flutter_gpiod_test_app
        run: flutter test -d "ODROID C4" -t odroidc4 integration_test/gpio_test.dart
